language: go

go:
  - 1.11.x

env:
  GO111MODULE=on

# this is necessary for fork builds to work
go_import_path: github.com/Pirionfr/lookatch-agent

before_install:
  - make init

script:
  - make dep
  - make format
  - make lint
  - make release
  - make test
  - make cover

after_success:
- bash <(curl -s https://codecov.io/bash)

