// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/Pirionfr/lookatch-agent/rpc (interfaces: ControllerClient,Controller_ChannelClient)

package mockrpc

import (
	context "context"

	rpc "github.com/Pirionfr/lookatch-agent/rpc"
	gomock "github.com/golang/mock/gomock"
	grpc "google.golang.org/grpc"
	metadata "google.golang.org/grpc/metadata"
)

// MockControllerClient Mock of ControllerClient interface
type MockControllerClient struct {
	ctrl     *gomock.Controller
	recorder *_MockControllerClientRecorder
}

// _MockControllerClientRecorder Recorder for MockControllerClient (not exported)
type _MockControllerClientRecorder struct {
	mock *MockControllerClient
}

// NewMockControllerClient New Mock ControllerClient
func NewMockControllerClient(ctrl *gomock.Controller) *MockControllerClient {
	mock := &MockControllerClient{ctrl: ctrl}
	mock.recorder = &_MockControllerClientRecorder{mock}
	return mock
}

// EXPECT return expected recorder
func (_m *MockControllerClient) EXPECT() *_MockControllerClientRecorder {
	return _m.recorder
}

// Channel mockrpc of channel
func (_m *MockControllerClient) Channel(_param0 context.Context, _param1 ...grpc.CallOption) (rpc.Controller_ChannelClient, error) {
	_s := []interface{}{_param0}
	for _, _x := range _param1 {
		_s = append(_s, _x)
	}
	ret := _m.ctrl.Call(_m, "Channel", _s...)
	ret0, _ := ret[0].(rpc.Controller_ChannelClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Channel mockrpc of channel
func (_mr *_MockControllerClientRecorder) Channel(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	_s := append([]interface{}{arg0}, arg1...)
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Channel", _s...)
}

// MockControllerChannelClient Mock of Controller_ChannelClient interface
type MockControllerChannelClient struct {
	ctrl     *gomock.Controller
	recorder *_MockControllerChannelClientRecorder
}

// Recorder for MockControllerChannelClient (not exported)
type _MockControllerChannelClientRecorder struct {
	mock *MockControllerChannelClient
}

// NewMockControllerChannelClient constructor of MockControllerChannelClient
func NewMockControllerChannelClient(ctrl *gomock.Controller) *MockControllerChannelClient {
	mock := &MockControllerChannelClient{ctrl: ctrl}
	mock.recorder = &_MockControllerChannelClientRecorder{mock}
	return mock
}

// EXPECT return expected recorder
func (_m *MockControllerChannelClient) EXPECT() *_MockControllerChannelClientRecorder {
	return _m.recorder
}

// CloseSend mockrpc of CloseSend
func (_m *MockControllerChannelClient) CloseSend() error {
	ret := _m.ctrl.Call(_m, "CloseSend")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseSend mockrpc of CloseSend
func (_mr *_MockControllerChannelClientRecorder) CloseSend() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "CloseSend")
}

// Context mockrpc of Context
func (_m *MockControllerChannelClient) Context() context.Context {
	ret := _m.ctrl.Call(_m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context mockrpc of Context
func (_mr *_MockControllerChannelClientRecorder) Context() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Context")
}

// Header mockrpc of Header
func (_m *MockControllerChannelClient) Header() (metadata.MD, error) {
	ret := _m.ctrl.Call(_m, "Header")
	ret0, _ := ret[0].(metadata.MD)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Header mockrpc of Header
func (_mr *_MockControllerChannelClientRecorder) Header() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Header")
}

// Recv mockrpc of Recv
func (_m *MockControllerChannelClient) Recv() (*rpc.Message, error) {
	ret := _m.ctrl.Call(_m, "Recv")
	ret0, _ := ret[0].(*rpc.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv mockrpc of Recv
func (_mr *_MockControllerChannelClientRecorder) Recv() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Recv")
}

// RecvMsg mockrpc of RecvMsg
func (_m *MockControllerChannelClient) RecvMsg(_param0 interface{}) error {
	ret := _m.ctrl.Call(_m, "RecvMsg", _param0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg mockrpc of RecvMsg
func (_mr *_MockControllerChannelClientRecorder) RecvMsg(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "RecvMsg", arg0)
}

// Send mockrpc of Send
func (_m *MockControllerChannelClient) Send(_param0 *rpc.Message) error {
	ret := _m.ctrl.Call(_m, "Send", _param0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send mockrpc of Send
func (_mr *_MockControllerChannelClientRecorder) Send(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Send", arg0)
}

// SendMsg mockrpc of SendMsg
func (_m *MockControllerChannelClient) SendMsg(_param0 interface{}) error {
	ret := _m.ctrl.Call(_m, "SendMsg", _param0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg mockrpc of SendMsg
func (_mr *_MockControllerChannelClientRecorder) SendMsg(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SendMsg", arg0)
}

// Trailer mockrpc of Trailer
func (_m *MockControllerChannelClient) Trailer() metadata.MD {
	ret := _m.ctrl.Call(_m, "Trailer")
	ret0, _ := ret[0].(metadata.MD)
	return ret0
}

// Trailer mockrpc of Trailer
func (_mr *_MockControllerChannelClientRecorder) Trailer() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Trailer")
}
