#!/usr/bin/expect -f

proc usage {} {
        send_user "Usage: rpm-sign gpgname passphrase rpmfile\n\n"
        exit
}

if {[llength $argv]!=3} usage

set gpgname [lindex $argv 0]
set passphrase [lindex $argv 1]
set rpmfile [lindex $argv 2]


spawn rpm --addsign -D "_signature gpg" -D "_gpg_name $gpgname" $rpmfile
expect {
-re "Enter pass *phrase: *" { log_user 0; send -- "$passphrase"; log_user 1; }
eof { catch wait rc; exit [lindex $rc 3]; }
timeout { close; exit; }
}
expect {
eof { catch wait rc; exit [lindex $rc 3]; }
timeout close
}

